#!/bin/sh

# Clean files generated by Design Compiler synthesis runs.
set -u

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
syn_dir=$(CDPATH= cd -- "${script_dir}/.." && pwd)

cd "${syn_dir}" || exit 1

echo "Cleaning generated synthesis files under ${syn_dir}"

removed=0

remove_path() {
    path=$1
    if [ -e "${path}" ] || [ -L "${path}" ]; then
        echo "Removing ${path}"
        rm -rf -- "${path}"
        removed=1
    fi
}

for path in \
    batch_* \
    alib-*
do
    [ -e "${path}" ] || [ -L "${path}" ] || continue
    remove_path "${path}"
done

for path in \
    dc.log \
    dc_*.log \
    command.log \
    filenames.log \
    view_command.log \
    default.svf
do
    [ -e "${path}" ] || [ -L "${path}" ] || continue
    remove_path "${path}"
done

if [ "${removed}" -eq 0 ]; then
    echo "No generated synthesis files found."
fi
