#!/usr/bin/env python
"""Generate per-module X-OPM data-preprocessing YAML configs (steps 1-5).

All 8 level-1 modules share the same benchmark list, test split, and rules; they
differ only in the module name, the power target column, and whether a random-
stimulus training augmentation exists.

    ~/anaconda3/bin/python config/xopm/gen_configs.py
"""
from __future__ import annotations

import os

MODULES = ["cp0", "idu", "ifu", "iu", "lsu", "rtu", "vidu", "vpu"]
# Modules that have random-stimulus training augmentation under rand_1cyc_20260830.
RAND_MODULES = {"cp0", "idu", "ifu", "iu", "vidu"}

CASES = ["cache", "conv_softmax", "coremark", "csr", "debug", "exception",
         "interrupt", "ISA_FP", "ISA_INT", "ISA_LS", "ISA_THEAD", "MMU"]
TEST_BENCHMARKS = ["conv_softmax", "coremark"]

_TEMPLATE = """# X-OPM data-preparation config for the {module} module (steps 1-5).
# AUTO-GENERATED by config/xopm/gen_configs.py -- edit the generator, not this file.
db_root: c906_db_net_1cyc_20260729
module: {module}
target: x_aq_core/Pc(x_aq_{module}_top)
output_dir: dataset_processed

cases:
{cases}

# Test set = conv_softmax + coremark (spec); all other benchmarks -> train.
test_benchmarks:
  - conv_softmax
  - coremark

# Random-stimulus training augmentation (cp0/idu/ifu/iu/vidu only). The rand
# case is always a TRAIN case.
rand_root: {rand_root}
rand_case_name: random

# Feature engineering:
#   control -> bit-split to single bits (invert _stall/_idle; drop dead bits)
#   data    -> per-cycle XOR toggle -> Hamming distance scalar, scaled by width
#   config  -> raw integer scaled by 2^width-1
hamming_count_initial: true
detect_duplicates: true
dedup_identical: true
drop_dead_control_bits: true

# classification keyword tokens (matched on the leaf signal name: after the last
# '/', bit-range stripped, lowercased). Control tokens match as WHOLE WORDS -- '_en'
# matches 'wr_en'/'wr_en0' but not 'entry'/'enable'. Data is a leaf that (1) matches an
# inclusion regex in data_patterns -- it must END with a data/din/dout core (optional
# leading '_') plus an optional suffix (raw, bank/bank0/bankx, or a numeric index): data,
# wdata, biu_lsu_rdata, dcache_data_din_bank0, icache_data_32 -- and (2) carries NONE of
# data_exclude_words as a whole '_'-delimited field, so read/write ports and sel/dirty
# buses (read_data_7 -> 'read' field, alias_data_sel, dcache_dirty_din) fall through to
# Config, while rdata/wdata buses (rd/wr are the head of the core, not a field) stay Data.
# Signals below any 'x_aq_spsram*' macro are dropped first.
rules:
  a_tokens: ["_en", "_vld", "_stall", "_busy", "_idle"]
  clk_token: clk
  clk_en_token: _en
  data_patterns: ["(?:^|_).*?(?:data|din|dout)(?:_?(?:raw|bank[0-9x]*|[0-9]+))*$"]
  data_exclude_words: ["sel", "dirty", "read", "rd", "write", "wr"]
  invert_tokens: ["_stall", "_idle"]
  exclude_segment_prefixes: ["x_aq_spsram"]
"""


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    cases_block = "\n".join(f"  - {c}" for c in CASES)
    for m in MODULES:
        rand_root = "rand_1cyc_20260830" if m in RAND_MODULES else "null"
        text = _TEMPLATE.format(module=m, cases=cases_block, rand_root=rand_root)
        path = os.path.join(here, f"{m}.yaml")
        with open(path, "w") as fh:
            fh.write(text)
        print(f"wrote {path} (rand={'yes' if m in RAND_MODULES else 'no'})")


if __name__ == "__main__":
    main()
