general:
  trainset_x_path: [db/ifu_output/MMU_func.pkl, db/ifu_output/cache_func.pkl]
  testset_x_path: [db/ifu_output/csr_func.pkl]
  y_path: [db/pwr/MMU_pwr.pkl, db/pwr/cache_pwr.pkl, db/pwr/csr_pwr.pkl]
  y_label: "/Pc(openC906)"
  seed: 42

preprocessing:
  drop_zero_var: true
  train_val_test_ratio: [0.8, 0.1, 0.1]
  avg_wsize: 1

feature_selection:
  algorithm: pearson
  top_k: 20
  hyperparams: {pearson: {}}

regression:
  algorithm: RuleFit
  intercept_on: true
  non_negative_coef_only: true
  hpo_timeout: 30
  hyperparams:
    RuleFit: {tree_size: 4, max_rules: 200, memory_par: 0.01}
