general:
  trainset_x_path: [db/ifu_output/MMU_func.pkl]
  testset_x_path: [db/ifu_output/csr_func.pkl]
  y_path: [db/pwr/MMU_pwr.pkl, db/pwr/csr_pwr.pkl]
  y_label: "/Pc(openC906)"
  seed: 42

preprocessing:
  drop_zero_var: true
  train_val_test_ratio: [0.8, 0.1, 0.1]
  avg_wsize: 1

feature_selection:
  algorithm: pearson
  top_k: 16
  hyperparams: {pearson: {}}

regression:
  algorithm: FT-Transformer
  intercept_on: false
  non_negative_coef_only: false
  hpo_timeout: 60
  hyperparams:
    FT-Transformer:
      batch_size: 128
      max_epochs: 20
      patience: 5
      d_token: 16
      n_blocks: 2
      n_heads: 2
      d_ffn: 32
